if exists("g:did_load_filetypes")
  filetype off
  filetype plugin indent off
endif

" pathogen woo
execute pathogen#infect()

" Forget being compatible with good ol' vi
set nocompatible


" Get that filetype stuff happening
filetype on
filetype plugin on
filetype indent on

" Turn on that syntax highlighting
syntax on

" Why is this not a default
set hidden

" Don't update the display while executing macros
set lazyredraw

" At least let yourself know what mode you're in
set showmode

" Enable enhanced command-line completion. Presumes you have compiled
" with +wildmenu.  See :help 'wildmenu'
set wildmenu

" Let's make it easy to edit this file (mnemonic for the key sequence is
" 'e'dit 'v'imrc)
nmap <silent> ,ev :e $MYVIMRC<cr>

" And to source this file as well (mnemonic for the key sequence is
" 's'ource 'v'imrc)
nmap <silent> ,sv :so $MYVIMRC<cr>

set modelines=5
set modeline

" sensible indenting defaults for what i do
set ts=2
set sw=2
set et
set autoindent

" User customisations. ',' is the 'leader char'
" :help leader
let mapleader=","


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vimcasts.org recommendations
"
" http://vimcasts.org/episodes/formatting-text-with-par/
:set formatprg=par\ -w72re

" http://vimcasts.org/episodes/how-to-fold/
" :help fold-methods
nnoremap <Space> za

" strip trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" comment/uncomment out code to marker 'a' as #MP#
nnoremap <leader># :'a,'bs/^/#MP#/<CR>
nnoremap <leader>3 :'a,'bs/#MP#//<CR>

" sensible vert-split hotkey
nnoremap <leader>w <C-w>v<C-w>l

