echo "Loading Profile"

# rbenv setup
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# virtualenv / hackercodex.com mavericks setup

# Set architecture flags
export ARCHFLAGS="-arch x86_64"

# Ensure user-installed binaries take precedence
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# Load .bashrc if it exists
test -f ~/.bashrc && source ~/.bashrc

#virtualenv wrapper (as per https://gist.github.com/munhitsu/1034876)
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh


alias bx='bundle exec'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gb='git branch'
alias gs='git status'
alias gd='git diff'
